name: toku_flutter_common
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  connectivity_plus: ^5.0.2
  cross_file: ^0.3.3+4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.7
  http: ^1.0.0
  injectable: ^2.1.1
  intl: ^0.19.0
  json_annotation: ^4.8.0
  meta: ^1.9.1
  pointer_interceptor: ^0.10.1+2
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
